package com.android.tomatoapp.common.utils;

import java.util.HashMap;
import java.util.Map;

public final class QuezonBarangays {
    private static final Map<String, String[]> BARANGAYS_BY_MUNICIPALITY = new HashMap<>();

    static {
        BARANGAYS_BY_MUNICIPALITY.put("Agdangan", new String[]{"Binagbag", "Dayap", "Ibabang Kinagunan", "Ilayang Kinagunan", "Kanlurang Calutan", "Kanlurang Maligaya", "Poblacion I", "Poblacion II", "Salvacion", "Silangang Calutan", "Silangang Maligaya", "Sildora"});
        BARANGAYS_BY_MUNICIPALITY.put("Alabat", new String[]{"Angeles", "Bacong", "Balungay", "Barangay 1", "Barangay 2", "Barangay 3", "Barangay 4", "Barangay 5", "Buenavista", "Caglate", "Camagong", "Gordon", "Pambilan Norte", "Pambilan Sur", "Villa Esperanza", "Villa Jesus Este", "Villa Jesus Weste", "Villa Norte", "Villa Victoria"});
        BARANGAYS_BY_MUNICIPALITY.put("Atimonan", new String[]{"Angeles", "Balubad", "Balugohin", "Barangay Zone 1", "Barangay Zone 2", "Barangay Zone 3", "Barangay Zone 4", "Buhangin", "Caridad Ibaba", "Caridad Ilaya", "Habingan", "Inaclagan", "Inalig", "Kilait", "Kulawit", "Lakip", "Lubi", "Lumutan", "Magsaysay", "Malinao Ibaba", "Malinao Ilaya", "Malusak", "Manggalayan Bundok", "Manggalayan Labak", "Matanag", "Montes Balaon", "Montes Kallagan", "Ponon", "Rizal", "San Andres Bundok", "San Andres Labak", "San Isidro", "San Jose Balatok", "San Rafael", "Santa Catalina", "Sapaan", "Sokol", "Tagbakin", "Talaba", "Tinandog", "Villa Ibaba", "Villa Ilaya"});
        BARANGAYS_BY_MUNICIPALITY.put("Buenavista", new String[]{"Bagong Silang", "Batabat Norte", "Batabat Sur", "Buenavista", "Bukal", "Bulo", "Cabong", "Cadlit", "Catulin", "Cawa", "De La Paz", "Del Rosario", "Hagonghong", "Ibabang Wasay", "Ilayang Wasay", "Lilukin", "Mabini", "Mabutag", "Magallanes", "Maligaya", "Manlana", "Masaya", "Poblacion", "Rizal", "Sabang Pinamasagan", "Sabang Piris", "San Diego", "San Isidro Ibaba", "San Isidro Ilaya", "San Pablo", "San Pedro", "San Vicente", "Siain", "Villa Aurora", "Villa Batabat", "Villa Magsaysay", "Villa Veronica"});
        BARANGAYS_BY_MUNICIPALITY.put("Burdeos", new String[]{"Aluyon", "Amot", "Anibawan", "Bonifacio", "Cabugao", "Cabungalunan", "Calutcot", "Caniwan", "Carlagan", "Mabini", "Palasan", "Poblacion", "San Rafael"});
        BARANGAYS_BY_MUNICIPALITY.put("Calauag", new String[]{"Agoho", "Anahawan", "Anas", "Apad Lutao", "Apad Quezon", "Apad Taisan", "Atulayan", "Baclaran", "Bagong Silang", "Balibago", "Bangkuruhan", "Bantolinao", "Barangay I", "Barangay II", "Barangay III", "Barangay IV", "Barangay V", "Bigaan", "Binutas", "Biyan", "Bukal", "Buli", "Dapdap", "Dominlog", "Do\u00f1a Aurora", "Guinosayan", "Ipil", "Kalibo", "Kapaluhan", "Katangtang", "Kigtan", "Kinalin Ibaba", "Kinalin Ilaya", "Kinamaligan", "Kumaludkud", "Kunalum", "Kuyaoyao", "Lagay", "Lainglaingan", "Lungib", "Mabini", "Madlangdungan", "Maglipad", "Maligaya", "Mambaling", "Manhulugin", "Marilag", "Mulay", "Pandanan", "Pansol", "Patihan", "Pinagbayanan", "Pinagkamaligan", "Pinagsakahan", "Pinagtalleran", "Rizal Ibaba", "Rizal Ilaya", "Sabang I", "Sabang II", "Salvacion", "San Quintin", "San Roque Ibaba", "San Roque Ilaya", "Santa Cecilia", "Santa Maria", "Santa Milagrosa", "Santa Rosa", "Santo Angel", "Santo Domingo", "Sinag", "Sumilang", "Sumulong", "Tabansak", "Talingting", "Tamis", "Tikiwan", "Tiniguiban", "Villa Magsino", "Villa San Isidro", "Vi\u00f1as", "Yaganak"});
        BARANGAYS_BY_MUNICIPALITY.put("Candelaria", new String[]{"Buenavista East", "Buenavista West", "Bukal Norte", "Bukal Sur", "Kinatihan I", "Kinatihan II", "Malabanban Norte", "Malabanban Sur", "Mangilag Norte", "Mangilag Sur", "Masalukot I", "Masalukot II", "Masalukot III", "Masalukot IV", "Masalukot V", "Masin Norte", "Masin Sur", "Mayabobo", "Pahinga Norte", "Pahinga Sur", "Poblacion", "San Andres", "San Isidro", "Santa Catalina Norte", "Santa Catalina Sur"});
        BARANGAYS_BY_MUNICIPALITY.put("Catanauan", new String[]{"Ajos", "Anusan", "Barangay 1", "Barangay 2", "Barangay 3", "Barangay 4", "Barangay 5", "Barangay 6", "Barangay 7", "Barangay 8", "Barangay 9", "Barangay 10", "Bolo", "Bulagsong", "Camandiison", "Canculajao", "Catumbo", "Cawayanin Ibaba", "Cawayanin Ilaya", "Cutcutan", "Dahican", "Doongan Ibaba", "Doongan Ilaya", "Gatasan", "Macpac", "Madulao", "Matandang Sabang Kanluran", "Matandang Sabang Silangan", "Milagrosa", "Navitas", "Pacabit", "San Antonio Magkupa", "San Antonio Pala", "San Isidro", "San Jose", "San Pablo", "San Roque", "San Vicente Kanluran", "San Vicente Silangan", "Santa Maria", "Tagabas Ibaba", "Tagabas Ilaya", "Tagbacan Ibaba", "Tagbacan Ilaya", "Tagbacan Silangan", "Tuhian"});
        BARANGAYS_BY_MUNICIPALITY.put("Dolores", new String[]{"Antonino", "Bagong Anyo", "Bayanihan", "Bulakin I", "Bulakin II", "Bungoy", "Cabatang", "Dagatan", "Kinabuhayan", "Maligaya", "Manggahan", "Pinagdanlayan", "Putol", "San Mateo", "Santa Lucia", "Silanganan"});
        BARANGAYS_BY_MUNICIPALITY.put("General Luna", new String[]{"Bacong Ibaba", "Bacong Ilaya", "Barangay 1", "Barangay 2", "Barangay 3", "Barangay 4", "Barangay 5", "Barangay 6", "Barangay 7", "Barangay 8", "Barangay 9", "Lavides", "Magsaysay", "Malaya", "Nieva", "Recto", "San Ignacio Ibaba", "San Ignacio Ilaya", "San Isidro Ibaba", "San Isidro Ilaya", "San Jose", "San Nicolas", "San Vicente", "Santa Maria Ibaba", "Santa Maria Ilaya", "Sumilang", "Villarica"});
        BARANGAYS_BY_MUNICIPALITY.put("General Nakar", new String[]{"Anoling", "Banglos", "Batangan", "Canaway", "Catablingan", "Lumutan", "Magsikap", "Mahabang Lalim", "Maigang", "Maligaya", "Minahan Norte", "Minahan Sur", "Pagsangahan", "Pamplona", "Pisa", "Poblacion", "Sablang", "San Marcelino", "Umiray"});
        BARANGAYS_BY_MUNICIPALITY.put("Guinayangan", new String[]{"A. Mabini", "Aloneros", "Arbismen", "Bagong Silang", "Balinarin", "Bukal Maligaya", "Cabibihan", "Cabong Norte", "Cabong Sur", "Calimpak", "Capuluan Central", "Capuluan Tulon", "Dancalan Caimawan", "Dancalan Central", "Danlagan Batis", "Danlagan Cabayao", "Danlagan Central", "Danlagan Reserva", "Del Rosario", "Dungawan Central", "Dungawan Paalyunan", "Dungawan Pantay", "Ermita", "Gapas", "Himbubulo Este", "Himbubulo Weste", "Hinabaan", "Ligpit Bantayan", "Lubigan", "Magallanes", "Magsaysay", "Manggagawa", "Manggalang", "Manlayo", "Poblacion", "Salakan", "San Antonio", "San Isidro", "San Jose", "San Lorenzo", "San Luis I", "San Luis II", "San Miguel", "San Pedro I", "San Pedro II", "San Roque", "Santa Cruz", "Santa Maria", "Santa Teresita", "Sintones", "Sisi", "Tikay", "Triumpo", "Villa Hiwasayan"});
        BARANGAYS_BY_MUNICIPALITY.put("Gumaca", new String[]{"Adia Bitaog", "Anonangin", "Bagong Buhay", "Bamban", "Bantad", "Batong Dalig", "Biga", "Binambang", "Buensuceso", "Bungahan", "Butaguin", "Calumangin", "Camohaguin", "Casasahan Ibaba", "Casasahan Ilaya", "Cawayan", "Gayagayaan", "Gitnang Barrio", "Hagakhakin", "Hardinan", "Inaclagan", "Inagbuhan Ilaya", "Labnig", "Laguna", "Lagyo", "Mabini", "Mabunga", "Malabtog", "Manlayaan", "Marcelo H. del Pilar", "Mataas na Bundok", "Maunlad", "Pagsabangan", "Panikihan", "PeÃ±afrancia", "Pipisik", "Progreso", "Rizal", "Rosario", "San Agustin", "San Diego", "San Diego Poblacion", "San Isidro Kanluran", "San Isidro Silangan", "San Juan de Jesus", "San Vicente", "Sastre", "Tabing Dagat", "Tumayan", "Villa Arcaya", "Villa Bota", "Villa Fuerte", "Villa M. Principe", "Villa Mendoza", "Villa Nava", "Villa Padua", "Villa Perez", "Villa TaÃ±ada", "Villa Victoria"});
        BARANGAYS_BY_MUNICIPALITY.put("Infanta", new String[]{"Abiawin", "Agos-agos", "Alitas", "Amolongin", "Anibong", "Antikin", "Bacong", "Balobo", "Bantilan", "Banugao", "Batican", "Binonoan", "Binulasan", "Boboin", "Catambungan", "Cawaynin", "Comon", "Dinahican", "Gumian", "Ilog", "Ingas", "Langgas", "Libjo", "Lual", "Magsaysay", "Maypulot", "Miswa", "Pilaway", "Pinaglapatan", "Poblacion 1", "Poblacion 38", "Poblacion 39", "Pulo", "Silangan", "Tongohin", "Tudturan"});
        BARANGAYS_BY_MUNICIPALITY.put("Jomalig", new String[]{"Apad", "Bukal", "Casuguran", "Gango", "Talisoy"});
        BARANGAYS_BY_MUNICIPALITY.put("Lopez", new String[]{"Bacungan", "Bagacay", "Banabahin Ibaba", "Banabahin Ilaya", "Bayabas", "Bebito", "Bigajo", "Binahian A", "Binahian B", "Binahian C", "Bocboc", "Buenavista", "Burgos", "Buyacanin", "Cagacag", "Calantipayan", "Canda Ibaba", "Canda Ilaya", "Cawayan", "Cawayanin", "Cogorin Ibaba", "Cogorin Ilaya", "Concepcion", "Danlagan", "De La Paz", "Del Pilar", "Del Rosario", "Esperanza Ibaba", "Esperanza Ilaya", "Gomez", "Guihay", "Guinuangan", "Guites", "Hondagua", "Ilayang Ilog A", "Ilayang Ilog B", "Inalusan", "Jongo", "Lalaguna", "Lourdes", "Mabanban", "Mabini", "Magallanes", "Magsaysay", "Maguilayan", "Mahayod-Hayod", "Mal-ay", "Mandoog", "Manguisian", "Matinik", "Monteclaro", "Pamampangin", "Pansol", "PeÃ±afrancia", "Pisipis", "Rizal (Poblacion)", "Rizal (Rural)", "Roma", "Rosario", "Samat", "San Andres", "San Antonio", "San Francisco A", "San Francisco B", "San Isidro", "San Jose", "San Miguel", "San Pedro", "San Rafael", "San Roque", "Santa Catalina", "Santa Elena", "Santa Jacobe", "Santa Lucia", "Santa Maria", "Santa Rosa", "Santa Teresa", "Santo NiÃ±o Ibaba", "Santo NiÃ±o Ilaya", "Silang", "Sugod", "Sumalang", "Talolong", "Tan-ag Ibaba", "Tan-ag Ilaya", "Tocalin", "Vegaflor", "VergaÃ±a", "Veronica", "Villa Aurora", "Villa Espina", "Villa Geda", "Villa Hermosa", "Villamonte", "Villanacaob"});
        BARANGAYS_BY_MUNICIPALITY.put("Lucban", new String[]{"Abang", "Aliliw", "Atulinao", "Ayuti", "Barangay 1", "Barangay 2", "Barangay 3", "Barangay 4", "Barangay 5", "Barangay 6", "Barangay 7", "Barangay 8", "Barangay 9", "Barangay 10", "Igang", "Kabatete", "Kakawit", "Kalangay", "Kalyaat", "Kilib", "Kulapi", "Mahabang Parang", "Malupak", "Manasa", "May-it", "Nagsinamo", "Nalunao", "Palola", "Piis", "Samil", "Tiawe", "Tinamnan"});
        BARANGAYS_BY_MUNICIPALITY.put("Macalelon", new String[]{"Amontay", "Anos", "Buyao", "Calantas", "Candangal", "Castillo", "Damayan", "Lahing", "Luctob", "Mabini Ibaba", "Mabini Ilaya", "Malabahay", "Mambog", "Masipag", "Olongtao Ibaba", "Olongtao Ilaya", "Padre Herrera", "Pag-asa", "Pajarillo", "Pinagbayanan", "Rizal", "Rodriquez", "San Isidro", "San Jose", "San Nicolas", "San Vicente", "Taguin", "Tubigan Ibaba", "Tubigan Ilaya", "Vista Hermosa"});
        BARANGAYS_BY_MUNICIPALITY.put("Mauban", new String[]{"Abo-abo", "Alitap", "Baao", "Bagong Bayan", "Balaybalay", "Bato", "Cagbalete I", "Cagbalete II", "Cagsiay I", "Cagsiay II", "Cagsiay III", "Concepcion", "Daungan", "Liwayway", "Lual", "Lual Rural", "Lucutan", "Luya-luya", "Mabato", "Macasin", "Polo", "Remedios I", "Remedios II", "Rizaliana", "Rosario", "Sadsaran", "San Gabriel", "San Isidro", "San Jose", "San Lorenzo", "San Miguel", "San Rafael", "San Roque", "San Vicente", "Santa Lucia", "Santo Angel", "Santo NiÃ±o", "Santol", "Soledad", "Tapucan"});
        BARANGAYS_BY_MUNICIPALITY.put("Mulanay", new String[]{"Ajos", "Amuguis", "Anonang", "Bagong Silang", "Bagupaye", "Barangay 1", "Barangay 2", "Barangay 3", "Barangay 4", "Bolo", "Buenavista", "Burgos", "Butanyog", "Canuyep", "F. Nanadiego", "Ibabang Cambuga", "Ibabang Yuni", "Ilayang Cambuga", "Ilayang Yuni", "Latangan", "Magsaysay", "Matataja", "Pakiing", "Patabog", "Sagongon", "San Isidro", "San Pedro", "Santa Rosa"});
        BARANGAYS_BY_MUNICIPALITY.put("Padre Burgos", new String[]{"Basiao", "Burgos", "Cabuyao Norte", "Cabuyao Sur", "Campo", "Danlagan", "Duhat", "Hinguiwin", "Kinagunan Ibaba", "Kinagunan Ilaya", "Lipata", "Marao", "Marquez", "Punta", "Rizal", "San Isidro", "San Vicente", "Sipa", "Tulay Buhangin", "Villapaz", "Walay", "Yawe"});
        BARANGAYS_BY_MUNICIPALITY.put("Pagbilao", new String[]{"Alupaye", "Antipolo", "AÃ±ato", "Bantigue", "Barangay 1 (Castillo)", "Barangay 2 (Daungan)", "Barangay 3 (Del Carmen)", "Barangay 4 (Parang)", "Barangay 5 (Santa Catalina)", "Barangay 6 (Tambak)", "Bigo", "Binahaan", "Bukal", "Ibabang Bagumbungan", "Ibabang Palsabangon", "Ibabang Polo", "Ikirin", "Ilayang Bagumbungan", "Ilayang Palsabangon", "Ilayang Polo", "Kanluran Malicboy", "Mapagong", "Mayhay", "Pinagbayanan", "Silangan Malicboy", "Talipan", "Tukalan"});
        BARANGAYS_BY_MUNICIPALITY.put("Panukulan", new String[]{"Balungay", "Bato", "Bonbon", "Calasumanga", "Kinalagti", "Libo", "Lipata", "Matangkap", "Milawid", "Pagitan", "Pandan", "Rizal", "San Juan"});
        BARANGAYS_BY_MUNICIPALITY.put("Patnanungan", new String[]{"Amaga", "Busdak", "Kilogan", "Luod", "Patnanungan Norte", "Patnanungan Sur"});
        BARANGAYS_BY_MUNICIPALITY.put("Perez", new String[]{"Bagong Pag-asa (Poblacion)", "Bagong Silang (Poblacion)", "Maabot", "Mainit Norte", "Mainit Sur", "Mapagmahal (Poblacion)", "Pagkakaisa (Poblacion)", "Pambuhan", "Pinagtubigan Este", "Pinagtubigan Weste", "Rizal", "Sangirin", "Villamanzano Norte", "Villamanzano Sur"});
        BARANGAYS_BY_MUNICIPALITY.put("Pitogo", new String[]{"Amontay", "Biga", "Bilucao", "Cabulihan", "Castillo", "Cawayanin", "Cometa", "Dalampasigan", "Dulong Bayan", "Gangahin", "Ibabang Burgos", "Ibabang Pacatin", "Ibabang PiÃ±a", "Ibabang Soliyao", "Ilayang Burgos", "Ilayang Pacatin", "Ilayang PiÃ±a", "Ilayang Soliyao", "Maaliw", "Manggahan", "Masaya", "Mayubok", "Nag-Cruz", "OsmeÃ±a", "Pag-asa", "Pamilihan", "Payte", "Pinagbayanan", "Poctol", "Quezon", "Quinagasan", "Rizalino", "Saguinsinan", "Sampaloc", "San Roque", "Sisirin", "Sumag Este", "Sumag Norte", "Sumag Weste"});
        BARANGAYS_BY_MUNICIPALITY.put("Plaridel", new String[]{"Central", "Concepcion", "Duhat", "Ilaya", "Ilosong", "M. L. Tumagay (Poblacion)", "Paang Bundok", "Pampaaralan", "Tanauan"});
        BARANGAYS_BY_MUNICIPALITY.put("Polillo", new String[]{"Anawan", "Atulayan", "Balesin", "BaÃ±adero", "Binibitinan", "Bislian", "Bucao", "Canicanian", "Kalubakis", "Languyin", "Libjo", "Pamatdan", "Pilion", "Pinaglubayan", "Poblacion", "Sabang", "Salipsip", "Sibulan", "Taluong", "Tamulaya-Anitong"});
        BARANGAYS_BY_MUNICIPALITY.put("Quezon", new String[]{"Apad", "Argosino", "Barangay I", "Barangay II", "Barangay III", "Barangay IV", "Barangay V", "Barangay VI", "Cagbalogo", "Caridad", "Cometa", "Del Pilar", "Guinhawa", "Gumubat", "Magsino", "MascariÃ±a", "MontaÃ±a", "Sabang", "Silangan", "Tagkawa", "Villa Belen", "Villa Francia", "Villa Gomez", "Villa Mercedes"});
        BARANGAYS_BY_MUNICIPALITY.put("Real", new String[]{"Bagong Silang", "Capalong", "Cawayan", "Kiloloran", "Llavac", "Lubayat", "Malapad", "Maragondon", "Masikap", "Maunlad", "Pandan", "Poblacion 61", "Poblacion I", "Tagumpay", "Tanauan", "Tignoan", "Ungos"});
        BARANGAYS_BY_MUNICIPALITY.put("Sampaloc", new String[]{"Alupay", "Apasan", "Banot", "Bataan", "Bayongon", "Bilucao", "Caldong", "Ibabang Owain", "Ilayang Owain", "Mamala", "San Bueno", "San Isidro", "San Roque", "Taquico"});
        BARANGAYS_BY_MUNICIPALITY.put("San Andres", new String[]{"Alibihaban", "Camflora", "Mangero", "Pansoy", "Poblacion", "Tala", "Talisay"});
        BARANGAYS_BY_MUNICIPALITY.put("San Antonio", new String[]{"Arawan", "Bagong Niing", "Balat Atis", "Briones", "Bulihan", "Buliran", "Callejon", "Corazon", "Loob", "Magsaysay", "Manuel del Valle Sr.", "Matipunso", "Niing", "Poblacion", "Pulo", "Pury", "Sampaga", "Sampaguita", "San Jose", "Sinturisan"});
        BARANGAYS_BY_MUNICIPALITY.put("San Francisco", new String[]{"Butanguiad", "Casay", "Cawayan I", "Cawayan II", "Don Juan Vercelos", "Huyon-Uyon", "Ibabang Tayuman", "Ilayang Tayuman", "Inabuan", "MabuÃ±ga", "Nasalaan", "Pagsangahan", "Poblacion", "Pugon", "Santo NiÃ±o", "Silongin"});
        BARANGAYS_BY_MUNICIPALITY.put("San Narciso", new String[]{"Abuyon", "Andres Bonifacio", "Bani", "Bayanihan", "Binay", "Buenavista", "Busokbusokan", "Calwit", "Guinhalinan", "Lacdayan", "Maguiting", "Maligaya", "Manlampong", "Pagdadamayan", "Pagkakaisa", "Punta", "Rizal", "San Isidro", "San Juan", "San Vicente", "Vigo Central", "Villa Aurin", "Villa Reyes", "White Cliff"});
        BARANGAYS_BY_MUNICIPALITY.put("Sariaya", new String[]{"Antipolo", "Balubal", "Barangay 1", "Barangay 2", "Barangay 3", "Barangay 4", "Barangay 5", "Barangay 6", "Bignay 1", "Bignay 2", "Bucal", "Canda", "CastaÃ±as", "Concepcion Banahaw", "Concepcion No. 1", "Concepcion Palasan", "Concepcion Pinagbakuran", "Gibanga", "Guisguis-San Roque", "Guisguis-Talon", "Janagdong 1", "Janagdong 2", "Limbon", "Lutucan 1", "Lutucan Bata", "Lutucan Malabag", "Mamala I", "Mamala II", "Manggalang 1", "Manggalang Tulo-tulo", "Manggalang-Bantilan", "Manggalang-Kiling", "Montecillo", "Morong", "Pili", "Sampaloc 1", "Sampaloc 2", "Sampaloc Bogon", "Sampaloc Santo Cristo", "Talaan Aplaya", "Talaanpantoc", "Tumbaga 1", "Tumbaga 2"});
        BARANGAYS_BY_MUNICIPALITY.put("Tagkawayan", new String[]{"Aldavoc", "Aliji", "Bagong Silang", "Bamban", "Bosigon", "Bukal", "Cabibihan", "Cabugwang", "Cagascas", "Candalapdap", "Casispalan", "Colong-colong", "Del Rosario", "Katimo", "Kinatakutan", "Landing", "Laurel", "Magsaysay", "Maguibuay", "Mahinta", "Malbog", "Manato Central", "Manato Station", "Mangayao", "Mansilay", "Mapulot", "Munting Parang", "Payapa", "Poblacion", "Rizal", "Sabang", "San Diego", "San Francisco", "San Isidro", "San Roque", "San Vicente", "Santa Cecilia", "Santa Monica", "Santo NiÃ±o I", "Santo NiÃ±o II", "Santo Tomas", "Seguiwan", "Tabason", "Tunton", "Victoria"});
        BARANGAYS_BY_MUNICIPALITY.put("Tiaong", new String[]{"Anastacia", "Aquino", "Ayusan I", "Ayusan II", "Barangay I", "Barangay II", "Barangay III", "Barangay IV", "Behia", "Bukal", "Bula", "Bulakin", "Cabatang", "Cabay", "Del Rosario", "Lagalag", "Lalig", "Lumingon", "Lusacan", "Paiisa", "Palagaran", "Quipot", "San Agustin", "San Francisco", "San Isidro", "San Jose", "San Juan", "San Pedro", "Tagbakin", "Talisay", "Tamisian"});
        BARANGAYS_BY_MUNICIPALITY.put("Unisan", new String[]{"Almacen", "Balagtas", "Balanacan", "Bonifacio", "Bulo Ibaba", "Bulo Ilaya", "Burgos", "Cabulihan Ibaba", "Cabulihan Ilaya", "Caigdal", "F. De Jesus", "General Luna", "Kalilayan Ibaba", "Kalilayan Ilaya", "Mabini", "Mairok Ibaba", "Mairok Ilaya", "Malvar", "Maputat", "Muliguin", "Pagaguasan", "Panaon Ibaba", "Panaon Ilaya", "Plaridel", "Poctol", "Punta", "R. Lapu-lapu", "R. Magsaysay", "Raja Soliman", "Rizal Ibaba", "Rizal Ilaya", "San Roque", "Socorro", "Tagumpay", "Tubas", "Tubigan"});
        BARANGAYS_BY_MUNICIPALITY.put("Tayabas", new String[]{"Alitao", "Alsam Ibaba", "Alsam Ilaya", "Alupay", "Angeles Zone I", "Angeles Zone II", "Angeles Zone III", "Angeles Zone IV", "Angustias Zone I", "Angustias Zone II", "Angustias Zone III", "Angustias Zone IV", "Anos", "Ayaas", "Baguio", "Banilad", "Bukal Ibaba", "Bukal Ilaya", "Calantas", "Calumpang", "Camaysa", "Dapdap", "Domoit Kanluran", "Domoit Silangan", "Gibanga", "Ibas", "Ilasan Ibaba", "Ilasan Ilaya", "Ipilan", "Isabang", "Katigan Kanluran", "Katigan Silangan", "Lakawan", "Lalo", "Lawigue", "Lita", "Malaoa", "Masin", "Mate", "Mateuna", "Mayowe", "Nangka Ibaba", "Nangka Ilaya", "Opias", "Palale Ibaba", "Palale Ilaya", "Palale Kanluran", "Palale Silangan", "Pandakaki", "Pook", "Potol", "San Diego Zone I", "San Diego Zone II", "San Diego Zone III", "San Diego Zone IV", "San Isidro Zone I", "San Isidro Zone II", "San Isidro Zone III", "San Isidro Zone IV", "San Roque Zone I", "San Roque Zone II", "Talolong", "Tamlong", "Tongko", "Valencia", "Wakas"});
        BARANGAYS_BY_MUNICIPALITY.put("Lucena", new String[]{"Barangay 1", "Barangay 2", "Barangay 3", "Barangay 4", "Barangay 5", "Barangay 6", "Barangay 7", "Barangay 8", "Barangay 9", "Barangay 10", "Barangay 11", "Barra", "Bocohan", "Cotta", "Dalahican", "Domoit", "Gulang-gulang", "Ibabang Dupay", "Ibabang Iyam", "Ibabang Talim", "Ilayang Dupay", "Ilayang Iyam", "Ilayang Talim", "Isabang", "Market View", "Mayao Castillo", "Mayao Crossing", "Mayao Kanluran", "Mayao Parada", "Mayao Silangan", "Ransohan", "Salinas", "Talao-talao"});
    }

    private QuezonBarangays() {}

    public static String[] getBarangays(String municipality) {
        String[] barangays = BARANGAYS_BY_MUNICIPALITY.get(municipality);
        return barangays == null ? null : barangays.clone();
    }
}